markdown: kramdown
title: Corndogit

# seo
description: "Chemistry grad trying to make it as a software developer, this is my personal site where I talk about my experiences."
image: https://avatars.githubusercontent.com/u/101812777?v=4
author:
  name: Nathan Brenton
  email: admin@corndogit.dev

url: "https://www.corndogit.dev"
baseurl: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
